# Generated by Django 3.0.5 on 2020-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autre',
            fields=[
                ('autre_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
