# Generated by Django 3.0.5 on 2020-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_autre'),
    ]

    operations = [
        migrations.AddField(
            model_name='autre',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
