# Generated by Django 3.0.5 on 2020-05-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_autre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autre',
            name='photo',
        ),
    ]
