# Generated by Django 3.0.5 on 2020-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_autre_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autre',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
